# https://github.com/gradle/gradle-build-action?tab=readme-ov-file#example-usage

name: Build

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: |
        chmod u+x gradlew
        ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qdaa
        path: build/libs/*.jar
